name: "Build"

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    env:
      CAKE_SETTINGS_ENABLESCRIPTCACHE: true
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"


    steps:
      - name: Checkout
        working-directory: c:/
        run: |
          git clone --single-branch --branch $("${{ github.ref }}".Replace('refs/heads/', '')) ${{ github.server_url }}/${{ github.repository }}.git repo

      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: friendlyanon/setup-vcpkg@v1
        with:
          path: repo/vcpkg
          committish: 1c9985b48b23ced4094420625237094deca32b8b

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Cache nuget packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('c:/repo/src/*/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Cache dotnet tools
        uses: actions/cache@v3
        with:
          path: c:/repo/tools
          key: ${{ runner.os }}-dotnet-tools-${{ hashFiles('build.cake', 'c:/repo/.config/dotnet-tools.json') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-tools-

      - name: Restore dotnet tools
        working-directory: c:/repo
        run: |
          dotnet tool restore

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: pwsh
        run: echo "dir=$(npm config get cache)" >> ${env:GITHUB_OUTPUT}

      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('c:/repo/src/papyrus-lang-vscode/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1

      - name: Install vcpkg packages
        working-directory: c:/repo
        run: |
          ../vcpkg/vcpkg.exe install --x-wait-for-lock --triplet x64-windows-static --x-install-root=c:/repo/vcpkg_installed/skyrim --x-feature=skyrim
          ../vcpkg/vcpkg.exe install --x-wait-for-lock --triplet x64-windows-static --x-install-root=c:/repo/vcpkg_installed/fallout4 --x-feature=fallout4

      - name: Build and Publish
        if: success()
        working-directory: c:/repo
        run: |
          dotnet cake
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TODO: Rename this stuff for clarity once release build artifacts are being created
          # TODO: Cleanup workflows for various event types in general
          RELEASE: ${{( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/prerelease') && github.event_name != 'pull_request' && github.event_name != 'pull_request_target' }}
          PRERELEASE: ${{ github.ref == 'refs/heads/prerelease' && github.event_name != 'pull_request' && github.event_name != 'pull_request_target' }}